name: nyzoridecaptain
description: "A driver application for managing rides, trips, and earnings efficiently."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.2
  dotted_line: ^3.2.3
  google_fonts: ^6.3.2
  country_picker: ^2.0.27
  firebase_storage: ^13.0.2
  smooth_page_indicator: ^1.2.1
  provider: ^6.1.5+1
  dotted_border: ^3.1.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  pinput: ^5.0.2
  flutter_localizations:
    sdk: flutter
  libphonenumber_plugin: ^0.3.3
  shared_preferences: ^2.5.3
  firebase_auth: ^6.1.0
  uuid: ^4.5.1
  bot_toast: ^4.1.3
  animated_text_kit: ^4.3.0
  slide_to_act: ^2.0.2
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  firebase_database: ^12.0.3
  animated_flip_counter: ^0.3.4
  lottie: ^3.1.0
  video_player: ^2.10.0
  dropdown_button2: ^2.3.9
  razorpay_flutter: ^1.4.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  googleapis_auth: ^2.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/nyzo_ride.png"
  min_sdk_android: 21

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/videos/
    - images/
 
